apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: jenkins-ingress
 namespace: ingress-basic 
 annotations:
  kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: technology-dp.ah.nl 
   http:
    paths:
    - path: /jenkins
      backend:
       serviceName: jenkins
       servicePort: 80
