apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: jenkins-ingress
 namespace: {{ .Values.jenkins.namespace }} 
 annotations:
  kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: {{ .Values.jenkins.ingress.hostname }}
   http:
    paths:
    - path: {{ .Values.jenkins.ingress.path }}
      backend:
       serviceName: jenkins-operator-http-jenkins
       servicePort: 80
